### ISSUE TITLE
missing spec key azure microservices

### ISSUE THREAD

**Issue by lks-hrsch** [thingsboard/thingsboard-pe-k8s#54]
Before the affinity key, the spec key is missing.

https://github.com/thingsboard/thingsboard-pe-k8s/blob/ead78c207baf873f0ba2591afd5caa7cec478f46/azure/microservices/tb-services.yml#L203

A solution could be:
```
  template:
    metadata:
      labels:
        app: tb-integration-executor
    spec:
      affinity:
        podAntiAffinity:
```
